# Generated by Django 2.2.1 on 2019-07-09 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20190618_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 7, 9, 18, 37, 18, 944509, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
