# Generated by Django 2.2.1 on 2019-07-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20190709_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='descripcion',
            field=models.CharField(max_length=999),
        ),
    ]
