# Generated by Django 2.2.1 on 2020-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_auto_20190711_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='talla',
            field=models.IntegerField(),
        ),
    ]
