# Generated by Django 2.2.1 on 2020-02-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_auto_20200216_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='talla',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
