# Generated by Django 2.2.1 on 2020-02-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_auto_20200216_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
