# Generated by Django 2.2.1 on 2020-02-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_auto_20200221_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ap',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
