# Generated by Django 2.2.1 on 2020-02-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_consulta_ap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='ap',
            field=models.DateField(),
        ),
    ]
