# Generated by Django 2.2.1 on 2020-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_auto_20200221_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='ap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='perimetro_encef',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
