# Generated by Django 2.2.1 on 2020-02-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.RecetaFooter')),
                ('header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.RecetaHeader')),
            ],
        ),
    ]
