# Generated by Django 2.2.1 on 2020-02-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_recetaheader_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaheader',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='header/logo'),
        ),
    ]
