# Generated by Django 2.2.1 on 2020-02-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_auto_20200219_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetafooter',
            name='footer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recetaheader',
            name='header',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recetasnippet',
            name='snippet',
            field=models.CharField(max_length=500),
        ),
    ]
