# Generated by Django 2.2.1 on 2020-02-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20200223_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetatemplate',
            name='default_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recetaheader',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='header/logo/'),
        ),
    ]
