# Generated by Django 2.2.1 on 2020-02-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_auto_20200224_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetatemplate',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
