# Generated by Django 2.2.1 on 2020-02-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_auto_20200227_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetafooter',
            name='default_footer',
        ),
        migrations.RemoveField(
            model_name='recetaheader',
            name='default_header',
        ),
    ]
