# Generated by Django 2.2.1 on 2020-03-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_recetasnippet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetatemplate',
            name='orientacion',
            field=models.CharField(choices=[('Iz', 'Left'), ('C', 'Center')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
