# Generated by Django 2.2.1 on 2020-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_recetatemplate_orientacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetatemplate',
            name='orientacion',
            field=models.CharField(choices=[('I', 'Left'), ('C', 'Center')], max_length=2),
        ),
    ]
