# Generated by Django 2.2.1 on 2020-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_auto_20200302_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetafooter',
            name='orientacion',
            field=models.CharField(choices=[('I', 'Left'), ('C', 'Center')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recetaheader',
            name='orientacion',
            field=models.CharField(choices=[('I', 'Left'), ('C', 'Center')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
