# Generated by Django 2.2.1 on 2020-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0014_auto_20200302_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetasnippet',
            name='name',
        ),
        migrations.AlterField(
            model_name='recetafooter',
            name='orientacion',
            field=models.CharField(choices=[('I', 'Izquierda'), ('C', 'Centrada')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recetaheader',
            name='orientacion',
            field=models.CharField(choices=[('I', 'Izquierda'), ('C', 'Centrada')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recetatemplate',
            name='orientacion',
            field=models.CharField(choices=[('I', 'Izquierda'), ('C', 'Centrada')], max_length=2),
        ),
    ]
