# Generated by Django 2.2.1 on 2019-05-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nya', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=11)),
                ('fecha_nac', models.DateField()),
                ('ciudad', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pacientes.Ciudad', verbose_name='Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Provincia'),
        ),
    ]
