# Generated by Django 2.2.1 on 2019-05-31 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '__first__'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='afiliado',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='obrasocial.Afiliado', verbose_name='Afiliado'),
        ),
    ]
