# Generated by Django 2.2.1 on 2019-05-31 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='afiliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrasocial.Afiliado', verbose_name='Afiliado'),
        ),
    ]
