# Generated by Django 2.2.1 on 2019-06-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20190531_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='afiliado',
        ),
    ]
