# Generated by Django 2.2.1 on 2019-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_paciente_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='peso_nac',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(default=''),
        ),
    ]
