# Generated by Django 2.2.1 on 2019-06-05 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20190605_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
