# Generated by Django 2.2.1 on 2020-02-12 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0006_auto_20190605_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('nya', models.CharField(max_length=100)),
                ('paciente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
        ),
    ]
