# Generated by Django 2.2.1 on 2020-02-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20200216_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_turno',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
