# Generated by Django 2.2.1 on 2019-05-31 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObraSocial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nya', models.CharField(default='Empty', max_length=200, verbose_name='Nombre Afiliado')),
                ('n_afiliado', models.IntegerField(default='999999')),
                ('ObraSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrasocial.ObraSocial')),
            ],
        ),
    ]
