# Generated by Django 2.2.1 on 2019-07-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0002_afiliado_paciente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='n_afiliado',
            field=models.CharField(default='999999', max_length=200),
        ),
    ]
