# Generated by Django 2.2.1 on 2020-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0004_auto_20190709_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='n_afiliado',
            field=models.CharField(default='Particular', max_length=200),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nya',
            field=models.CharField(blank=True, default='Empty', max_length=200, null=True, verbose_name='Nombre Afiliado'),
        ),
    ]
